### PR TITLE
Cde updates

### PR DESCRIPTION
**Pull request by ipapapa**
* Local building was failing. Updating nebula and related packages
* Stabilizing Dyno version from RC to stable
* Naming Convention for v2 with Redis Pipeline

### CODE REVIEW

**Review by falu2010-netflix — APPROVED** [review]
This will require code updates in Conductor as it uses RedisQueue which is renamed to RedisPipelineQueue.

**Comment by ipapapa** [comment]
@falu2010-netflix I do not believe you need to change something as Conductor is not using Redis Pipelines. See more info: https://github.com/Netflix/conductor/blob/master/redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/queue/DynoQueueDAO.java#L25-L30

**Comment by falu2010-netflix** [comment]
@ipapapa you are correct it does not use anything from v2. I got confused with https://github.com/Netflix/dyno-queues/blob/dev/dyno-queues-redis/src/main/java/com/netflix/dyno/queues/redis/RedisQueues.java.

**Comment by smukil** [comment]
@ipapapa Saw this late, but LGTM.

**Pull request merged**
